### ISSUE TITLE
Link to Actuarial Resources

### ISSUE THREAD

**Issue by edent** [r0w4n/cs-pension#12]
Thanks for this. I wasn't able to get the Excel macros to run on LibreOffice, so this has been very handy.

When I was trying to calculate things by hand, CSP sent me a link to https://www.civilservicepensionscheme.org.uk/knowledge-centre/resources/actuarial-factors/

I *think* they may be more accurate than the macros. But, either way, it might be sensible to link to them as the definitive source of data.

**Comment by r0w4n** [comment]
Hello @edent thank you for taking the time to suggest this. The calculator already using the actuarial factors to make the calculations the link to get methods that get the actuaries is [here](https://github.com/r0w4n/cs-pension/blob/main/src/pension.js#L226) And the actuaries and factor data can be found [here](https://github.com/r0w4n/cs-pension/tree/main/src/data) 

Please let me know if have mis-understood your suggestion.
