### ISSUE TITLE
EPA coverage and commutation rates

### ISSUE THREAD

**Issue by MichaelS12345** [r0w4n/cs-pension#24]
1)  I have EPA covering my baseline pension entitlement (about 15% of my total) but the rest comes from added pension/transfer in to which EPA does not apply, it would be nice to be able to model this

2) What commutation rate tables are you using, I understand these are in the process of being updated but have not seen the refreshed figures anywhere yet

Thanks

**Comment by r0w4n** [comment]
Hello,

I'd say the epa part of the modler is pretty poor at the moment and needs
to looking at. I planned to do some work at Christmas on this but
circumstances look like this is unlikely. If you had some time you could
contribute to the modler.

Else I'll get to this feature request on my next motivation cycle.

Kind regards,

Rowan

**Comment by MichaelS12345** [comment]
Thanks, your work is much appreciated.  Wish I had the time to get my head around the coding but can't see that happening until after I retire!

Are you able to point me to the commutation rates table you used for the early retirement (as an aside the new state pension is the 22/23 figure, probably an easy fix to move to the 223/24?)

**Comment by MichaelS12345** [comment]
Apologies, meant reduction factors not commutation factors - current set are here which I guess are what you have used but they are supposed to be being updated imminently.

https://www.civilservicepensionscheme.org.uk/media/oislhmme/early-and-late-retirement-factors-and-guidance-alpha.pdf

pension.js
const statePension = 9660;

value for 23/24 is 10636
value for 24/25 will be 11542

**Comment by r0w4n** [comment]
@MichaelS12345 I've updated the calculator in have the state pension to be a user input defaulting to the current value for state pension.
