### ISSUE TITLE
Additions

### ISSUE THREAD

**Issue by HUTiger86** [r0w4n/cs-pension#34]
**Describe the solution you'd like**
Include annual pay rise and inflation % fields. Not sure how easy/complicated that is!

Great tool, thanks for creating :)

**Comment by r0w4n** [comment]
Hey @HUTiger86, I've thought about including inflation in the past. The way I see it is that inflation is a relative thing and completely unpredictable. Relative in that we have a sense of how much things cost now, and the amount that is shown in the calculator is how much you will have in your pocket when you retire (negating inflation). So you have a relative sense on whether that is enough. Your pension will go up with inflation. And so will your sense of how much things are worth.

With regards to the pay rise, I don't think I want to add this either.
